# Generated by Django 4.0.5 on 2022-06-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('occupant_name', models.CharField(max_length=254)),
                ('occupant_email', models.EmailField(max_length=254)),
                ('occupant_occupation', models.CharField(max_length=50)),
                ('number_night', models.IntegerField()),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=60)),
            ],
        ),
    ]
